# texts.py

TEXTS = {
    'uk': {
        'sub_expired': "⚠️ **Ваша підписка закінчилася або призупинена.**\nБудь ласка, зверніться до адміністратора.",
        'owner_panel': "🏢 **Кабінет власника: {name}**",
        'manager_panel': "👨‍💼 **Панель менеджера: {name}**",
        'courier_panel': "🛵 **Робоче місце кур'єра: {name}**",
        'no_zvit_access': "❌ У вас немає доступу до звітів.",
        'no_access': "⛔️ У вас немає прав для цієї дії.",
        'zvit_empty': "📭 Сьогодні ще немає доставлених замовлень для звіту.",
        'zvit_title': "📊 ЗВІТ ({time})\n➖ ➖ ➖ ➖ ➖\n",
        'zvit_cash': "💰 Готівка: {cash} {cur}\n",
        'zvit_term': "💳 Термінал: {term} {cur}",
        'boss_panel': "Вітаю, Бос! 🫡\nОсь доступ до керування всіма бізнесами:",
        'dont_understand': "Я вас не розумію 🤷‍♂️",
        'link_invalid': "🛑 Це посилання недійсне, застаріло або було анульоване власником!",
        'link_error': "❌ Сталася помилка при перевірці посилання. Спробуйте пізніше.",
        'role_c_full': "Кур'єра 🛵",
        'role_m_full': "Менеджера 👨‍💼",
        'invite_welcome': "👋 Вітаємо!\nВи отримали запрошення на посаду **{role}** у заклад **{biz_name}**.\n\n✏️ Введіть ваше Прізвище та Ім'я, щоб приєднатися до команди:",
        'start_welcome': "🌟 **Вітаємо в DelivePro!**\n\nЕволюція вашої доставки починається тут. Натисніть кнопку нижче, щоб налаштувати свій бізнес.",
        'biz_already_exists': "⚠️ У вас вже є зареєстрований заклад. Якщо хочете змінити налаштування — відкрийте панель керування.",
        'biz_created': "🎉 **Вітаємо! Ваш бізнес '{biz_name}' успішно створено.**\n📦 **Тариф:** {plan} (Активовано 7 днів тріалу)\n\nТепер ви можете перейти до повноцінного керування 👇",
        'reg_error': "❌ Сталася помилка при реєстрації. Перевірте логи.",
        'pay_cash': "Готівка",
        'pay_terminal': "Термінал",
        'pay_online': "Онлайн",
        'apt_prefix': "Кв/Оф: {apt}",
        'code_prefix': "Домофон: {code}",
        'details_prefix': "🏢 Деталі: {details}\n",
        'status_active_full': "Статус: 🟢 Активний",
        'status_done_full': "Статус: ✅ ДОСТАВЛЕНО",
        'order_new': "📦 **НОВЕ ЗАМОВЛЕННЯ #{short_id}**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n{status}\n\n📍 **Адреса:** {address}\n{details_text}📞 **Тел:** {phone} ({client_name})\n{pay_icon} **Оплата:** {amount} {cur} ({pay_type})\n",
        'comment_prefix': "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n🗣 **Коментар:** {comment}\n",
        'btn_route': "🗺 Відкрити маршрут",
        'btn_finish': "✅ Доставлено (Закрити)",
        'order_sent': "✅ Замовлення #{short_id} успішно створено та відправлено кур'єру!",
        'order_save_err': "❌ Помилка при збереженні замовлення в базу.",
        'order_send_err': "❌ Сталася помилка при відправці замовлення.",
        'broadcast_no_access': "❌ У вас немає прав для розсилки.",
        'broadcast_empty': "📭 Немає жодного власника для розсилки.",
        'broadcast_start': "🚀 Починаю розсилку для {count} клієнтів. Зачекайте...",
        'broadcast_msg': "🔔 **Повідомлення від платформи:**\n\n{text}",
        'broadcast_done': "✅ Розсилка успішно завершена!\nДоставлено: **{sent} з {total}** користувачів.",
        'role_c': "Кур'єр",
        'role_m': "Менеджер",
        'staff_added': "✅ Вітаємо, {name}! Ви успішно приєдналися до команди як {role}.",
        'staff_add_err': "❌ Помилка при додаванні. Спробуйте ще раз.",
        'already_registered': "✅ Ви вже зареєстровані як {role} в цьому закладі.",
        'finish_success': "🎉 Замовлення успішно завершено! Гроші в касі.",
        'finish_notify': "✅ **Замовлення доставлено!**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n📦 Номер: `#{short_id}`\n💰 Сума: {amount} {cur}\n🛵 Кур'єр: {courier_name}\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n🏠 Кур'єр повертається на базу.",
        'finish_err': "❌ Помилка завершення",
        'sa_empty': "📭 Бізнесів поки немає.",
        'sa_manage': "🚀 Керування SaaS:",
        'sa_changed': "Статус змінено!",
        'btn_open_app': "🚀 Відкрити DelivePro",
        'btn_dashboard': "📊 Дашборд",
        'btn_map': "🗺 Карта замовлень",
        'btn_report': "📊 Зробити звіт",
        'btn_settings': "⚙️ Налаштування бізнесу",
        'btn_staff': "👥 Персонал",
        'btn_new_order': "📝 Нове замовлення",
        'btn_active_orders': "📂 Активні замовлення",
        'btn_schedule': "📅 Графік роботи",
        'btn_my_deliveries': "📦 Мої доставки",
        'btn_boss_panel': "👑 Панель Власника",
        'expired_trial_text': "⚠️ **Ваш тестовий період або підписка завершилася!**\n\nЩоб продовжити роботу, будь ласка, відкрийте Дашборд.",
        'expired_staff_text': "⚠️ **Підписка закладу завершилася.**\n\nЗверніться до власника для поновлення.",
        'btn_open_dashboard': "📊 Відкрити Дашборд",
        'expired_no_orders': "⚠️ Підписка закінчилася. Ви не можете створювати нові замовлення. Відкрийте Дашборд.",
        'free_order_created': "🟢 **ВІЛЬНЕ ЗАМОВЛЕННЯ #{short_id}**\n\nЗамовлення додано на карту! Відкрийте карту, щоб призначити кур'єра.\n🔗 *Лінк для відстеження клієнтом:*\n`{tracking_link}`",
        'order_assigned_success': "✅ Замовлення #{short_id} успішно призначено!",
        'order_assign_error': "❌ Помилка при призначенні замовлення.",
        'order_already_assigned': "⚠️ Це замовлення вже призначено кур'єру.",
        'expired_no_report': "⚠️ Підписка закінчилася. Відкрийте Дашборд для оплати.",
        'tracking_link_label': "🔗 *Лінк для відстеження клієнтом:*\n`{tracking_link}`",
        'order_status_active': "🟢 Активний — хто перший, той і везе!",
        'order_status_active_short': "🟢 Активний",
        'order_status_delivering': "🟡 В дорозі (Везтиме: {courier})",
        'order_status_closed': "🔴 Закрито ({time}, {courier} - {pay_icon})",
        'order_label': "ЗАМОВЛЕННЯ",
        'order_label_free': "ВІЛЬНЕ ЗАМОВЛЕННЯ",
        'order_label_new': "НОВЕ ЗАМОВЛЕННЯ",
        'order_label_no_courier': "(без кур'єра)",
        'order_status_lbl': "Статус",
        'order_address_lbl': "Адреса",
        'order_details_lbl': "Деталі",
        'order_client_lbl': "Клієнт",
        'order_tel_lbl': "Тел",
        'order_comment_lbl': "Коментар",
        'order_pay_cash_line': "💵 Готівка: {amount} {cur}",
        'order_pay_terminal_line': "🏧 Термінал: {amount} {cur}",
        'order_pay_online_line': "💳 Оплата: ОНЛАЙН (Сплачено)",
        'btn_take_order': "✅ Взяти замовлення",
        'btn_call': "📞 Подзвонити",
        'btn_close_online': "✅ Закрити (Онлайн оплачено)",
        'btn_close_cash': "💵 Готівка — {amount} {cur}",
        'btn_close_terminal': "🏧 Термінал — {amount} {cur}",
        'closing_order': "✅ Закриваємо замовлення...",
        'order_not_found': "❌ Замовлення не знайдено.",
        'order_format_error': "❌ Помилка формату callback.",
        'order_already_closed': "✅ Замовлення вже закрите.",
        'order_wrong_courier': "⛔️ Це замовлення веде інший кур'єр.",
        'courier_not_in_staff': "⛔️ Кур'єра не знайдено в персоналі цього закладу.",
        'free_order_manager_notify': "📦 <b>НОВЕ ЗАМОВЛЕННЯ #{short_id}</b> (без кур'єра)\n\n📍 <b>Адреса:</b> {address}\n👤 <b>Клієнт:</b> {client_name}\n📞 <b>Тел:</b> {phone}\n💰 <b>Сума:</b> {amount} {cur}\n⚠️ Призначте кур'єра через карту замовлень.",
        'courier_returns': "🏠 Кур'єр повертається на базу.",
        'courier_free': "✅ Кур'єр __вільний__ для роботи.",
        'report_courier_line': "👤 {name}: {count} зам.",
        'report_online_line': " | 🌐 {count} онл. ({sum})",
        'report_online_summary': "\n🌐 Онлайн: {count} замовлень | {sum} {cur} (сплачено)",
        'generic_error': "❌ Помилка: {error}",
        'ticket_sent': "✅ <b>Тікет успішно відправлено!</b> Наша служба підтримки зв'яжеться з вами найближчим часом.",
        'ticket_admin_msg': "🆘 <b>НОВИЙ ТІКЕТ ПІДТРИМКИ</b>\n\n🏢 <b>Бізнес ID:</b> <code>{biz_id}</code>\n👤 <b>Від:</b> <a href='tg://user?id={user_id}'>Клієнт (ID: {user_id})</a>\n🏷 <b>Категорія:</b> {reason}\n📌 <b>Тема:</b> {topic}\n〰️〰️〰️〰️〰️〰️〰️〰️\n💬 <b>Повідомлення:</b>\n<i>{message}</i>",
        'btn_call_regular': "📞 Подзвонити",
        'btn_assign_courier': "🛵 Призначити кур'єра",
        'pos_order_new': "🔥 <b>НОВЕ ЗАМОВЛЕННЯ З {source}!</b>\n\n👤 <b>Клієнт:</b> {client}\n📞 <b>Телефон:</b> {phone}\n📍 <b>Адреса:</b> {address}\n💰 <b>Сума:</b> {amount} {cur}",
        'pos_order_comment': "\n💬 <b>Коментар:</b> <i>{comment}</i>",
        'pro_activated': "🎉 <b>Вітаємо! Оплата успішна!</b>\nТариф <b>PRO</b> активовано. Дякуємо за довіру! 🚀",
        'subscription_expired': "⚠️ <b>Вашу підписку скасовано.</b>\nДля поновлення відкрийте Дашборд.",
        'name_invalid': "⚠️ Ім'я має бути від 2 до 50 символів і не починатися з /",
        'btn_my_active_orders': "📦 Мої замовлення",
        'client_default': "Клієнт",
        # --- ЗМІНА КУР'ЄРА ---
        'btn_start_shift': "🟢 Розпочати зміну",
        'btn_close_shift': "🔴 Закрити зміну",
        'shift_already_active': "⚠️ У вас вже є активна зміна. Спочатку закрийте її.",
        'shift_send_start_photo': "📸 Зробіть фото спідометра перед початком зміни та надішліть його сюди.",
        'shift_send_start_km': "✅ Фото отримано!\n\nТепер введіть поточний кілометраж числом (наприклад: <b>12340</b>):",
        'shift_started': "✅ Зміну розпочато!\n\n🛣 Кілометраж <b>{name}</b> на початок зміни: <b>{km} км</b>\n\nУдачі на маршруті! 🚀",
        'shift_photo_forwarded': "📸 <b>Фото спідометра — початок зміни</b>\n👤 Кур'єр: <b>{name}</b>\n🛣 Км: <b>{km}</b>",
        'shift_notify_start': "🟢 Кур'єр <b>{name}</b> розпочав зміну\n🛣 Км: <b>{km}</b>",
        'shift_notify_end': "🔴 Кур'єр <b>{name}</b> завершив зміну\n🛣 Км: <b>{km}</b>",
        'shift_end_photo_forwarded': "📸 <b>Фото спідометра — кінець зміни</b>\n👤 Кур'єр: <b>{name}</b>\n🛣 Км: <b>{km}</b>",
        'shift_no_active': "⚠️ У вас немає активної зміни. Спочатку розпочніть зміну.",
        'shift_send_end_photo': "📸 Надішліть фото спідометра для закриття зміни.",
        'shift_send_end_km': "✅ Фото отримано!\n\nВведіть поточний кілометраж числом:",
        'shift_km_invalid': "❌ Невірний формат. Введіть ціле число, наприклад: <b>12500</b>",
        'shift_km_less_than_start': "❌ Кінцевий кілометраж не може бути меншим за початковий (<b>{start_km} км</b>). Спробуйте ще раз.",
        'shift_report': (
            "📊 <b>Звіт за зміну — {name}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "🛣 Кілометраж за зміну: <b>{km} км</b>\n"
            "📦 Замовлень: <b>{orders}</b>\n"
            "💵 Готівка: <b>{cash} {cur}</b>\n"
            "💳 Термінал: <b>{term} {cur}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "🚗 До сплати за км: <b>{km} × {rate} = {km_total} {cur}</b>\n"
            "🏦 До здачі в касу: <b>{cash} − {km_total} = {to_pay} {cur}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "✅ Зміну закрито. Гарного відпочинку! 🏠"
        ),
        'shift_admin_report_header': "📊 <b>ЗВІТ ЗМІН — {date}</b>\n➖➖➖➖➖➖➖➖➖\n",
        'shift_admin_report_line': (
            "👤 <b>{name}</b>\n"
            "  🛣 Км: {km} | 📦 Зам: {orders} | 💵 {cash} / 💳 {term} {cur}\n"
            "  🚗 За км: {km_total} {cur} | 🏦 В касу: {to_pay} {cur}\n\n"
        ),
        'shift_admin_report_empty': "📭 Сьогодні ще немає закритих змін.",
        'btn_shift_view_photo': "📸 Фото ({name})",
        'shift_photo_start_caption': "📸 Початок зміни — {name}\n🛣 {km} км",
        'shift_photo_end_caption': "📸 Кінець зміни — {name}\n🛣 {km} км",
        'shift_photo_not_found': "❌ Фото не знайдено.",
        'btn_shift_report': "📋 Звіт змін",
        'start_menu_hint': "Натисніть /start щоб відкрити меню.",
        'order_taken_by_other': "⚠️ Це замовлення вже взяте іншим кур\'єром.",
        'order_take_failed': "⚠️ Не вдалось взяти замовлення. Спробуйте ще раз.",
        'late_header': "🚨 ЗАПІЗНЕННЯ ЗАМОВЛЕННЯ!",
        'late_order_lbl': "Замовлення",
        'late_addr_lbl': "Адреса",
        'late_phone_lbl': "Тел",
        'late_courier_lbl': "Кур\'єр",
        'late_mins_msg': "Запізнення вже на {mins} хв!",
        'shift_on_duty': "🟢 <b>Зараз на зміні:</b>",
        'btn_photo_start': "📸 {name} — початок",
        'btn_photo_end': "📸 {name} — кінець",
        'courier_since': "з {time} · {orders} зам.",
    },
    'ru': {
        'sub_expired': "⚠️ **Ваша подписка закончилась или приостановлена.**\nПожалуйста, обратитесь к администратору.",
        'owner_panel': "🏢 **Кабинет владельца: {name}**",
        'manager_panel': "👨‍💼 **Панель менеджера: {name}**",
        'courier_panel': "🛵 **Рабочее место курьера: {name}**",
        'no_zvit_access': "❌ У вас нет доступа к отчетам.",
        'no_access': "⛔️ У вас нет прав для этого действия.",
        'zvit_empty': "📭 Сегодня еще нет доставленных заказов для отчета.",
        'zvit_title': "📊 ОТЧЕТ ({time})\n➖ ➖ ➖ ➖ ➖\n",
        'zvit_cash': "💰 Наличные: {cash} {cur}\n",
        'zvit_term': "💳 Терминал: {term} {cur}",
        'boss_panel': "Привет, Босс! 🫡\nВот доступ к управлению всеми бизнесами:",
        'dont_understand': "Я вас не понимаю 🤷‍♂️",
        'link_invalid': "🛑 Эта ссылка недействительна, устарела или была аннулирована владельцем!",
        'link_error': "❌ Произошла ошибка при проверке ссылки. Попробуйте позже.",
        'role_c_full': "Курьера 🛵",
        'role_m_full': "Менеджера 👨‍💼",
        'invite_welcome': "👋 Приветствуем!\nВы получили приглашение на должность **{role}** в заведение **{biz_name}**.\n\n✏️ Введите ваши Имя и Фамилию, чтобы присоединиться к команде:",
        'start_welcome': "🌟 **Добро пожаловать в DelivePro!**\n\nЭволюция вашей доставки начинается здесь. Нажмите кнопку ниже, чтобы настроить свой бизнес.",
        'biz_already_exists': "⚠️ У вас уже есть зарегистрированное заведение. Если хотите изменить настройки — откройте панель управления.",
        'biz_created': "🎉 **Поздравляем! Ваш бизнес '{biz_name}' успешно создан.**\n📦 **Тариф:** {plan} (Активировано 7 дней триала)\n\nТеперь вы можете перейти к полноценному управлению 👇",
        'reg_error': "❌ Произошла ошибка при регистрации.",
        'pay_cash': "Наличные",
        'pay_terminal': "Терминал",
        'pay_online': "Онлайн",
        'apt_prefix': "Кв/Оф: {apt}",
        'code_prefix': "Домофон: {code}",
        'details_prefix': "🏢 Детали: {details}\n",
        'status_active_full': "Статус: 🟢 Активный",
        'status_done_full': "Статус: ✅ ДОСТАВЛЕНО",
        'order_new': "📦 **НОВЫЙ ЗАКАЗ #{short_id}**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n{status}\n\n📍 **Адрес:** {address}\n{details_text}📞 **Тел:** {phone} ({client_name})\n{pay_icon} **Оплата:** {amount} {cur} ({pay_type})\n",
        'comment_prefix': "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n🗣 **Комментарий:** {comment}\n",
        'btn_route': "🗺 Открыть маршрут",
        'btn_finish': "✅ Доставлено (Закрыть)",
        'order_sent': "✅ Заказ #{short_id} успешно создан и отправлен курьеру!",
        'order_save_err': "❌ Ошибка при сохранении заказа в базу.",
        'order_send_err': "❌ Произошла ошибка при отправке заказа.",
        'broadcast_no_access': "❌ У вас нет прав для рассылки.",
        'broadcast_empty': "📭 Нет ни одного владельца для рассылки.",
        'broadcast_start': "🚀 Начинаю рассылку для {count} клиентов. Подождите...",
        'broadcast_msg': "🔔 **Сообщение от платформы:**\n\n{text}",
        'broadcast_done': "✅ Рассылка успешно завершена!\nДоставлено: **{sent} из {total}** пользователей.",
        'role_c': "Курьер",
        'role_m': "Менеджер",
        'staff_added': "✅ Добро пожаловать, {name}! Вы успешно присоединились к команде как {role}.",
        'staff_add_err': "❌ Ошибка при добавлении. Попробуйте ещё раз.",
        'already_registered': "✅ Вы уже зарегистрированы как {role} в этом заведении.",
        'finish_success': "🎉 Заказ успешно завершён! Деньги в кассе.",
        'finish_notify': "✅ **Заказ доставлен!**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n📦 Номер: `#{short_id}`\n💰 Сумма: {amount} {cur}\n🛵 Курьер: {courier_name}\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n🏠 Курьер возвращается на базу.",
        'finish_err': "❌ Ошибка завершения",
        'sa_empty': "📭 Бизнесов пока нет.",
        'sa_manage': "🚀 Управление SaaS:",
        'sa_changed': "Статус изменён!",
        'btn_open_app': "🚀 Открыть DelivePro",
        'btn_dashboard': "📊 Панель",
        'btn_map': "🗺 Карта заказов",
        'btn_report': "📊 Сделать отчет",
        'btn_settings': "⚙️ Настройки бизнеса",
        'btn_staff': "👥 Персонал",
        'btn_new_order': "📝 Новый заказ",
        'btn_active_orders': "📂 Активные заказы",
        'btn_schedule': "📅 График работы",
        'btn_my_deliveries': "📦 Мои доставки",
        'btn_boss_panel': "👑 Панель Владельца",
        'expired_trial_text': "⚠️ **Ваш пробный период или подписка истекли!**\n\nЧтобы продолжить работу, пожалуйста, откройте Панель.",
        'expired_staff_text': "⚠️ **Подписка заведения истекла.**\n\nСвяжитесь с владельцем для продления.",
        'btn_open_dashboard': "📊 Открыть Панель",
        'expired_no_orders': "⚠️ Подписка истекла. Вы не можете создавать новые заказы. Откройте Панель.",
        'free_order_created': "🟢 **СВОБОДНЫЙ ЗАКАЗ #{short_id}**\n\nЗаказ добавлен на карту! Откройте карту, чтобы назначить курьера.\n🔗 *Ссылка для отслеживания клиентом:*\n`{tracking_link}`",
        'order_assigned_success': "✅ Заказ #{short_id} успешно назначен!",
        'order_assign_error': "❌ Ошибка при назначении заказа.",
        'order_already_assigned': "⚠️ Этот заказ уже назначен курьеру.",
        'expired_no_report': "⚠️ Подписка истекла. Откройте Панель для оплаты.",
        'tracking_link_label': "🔗 *Ссылка для отслеживания клиентом:*\n`{tracking_link}`",
        'order_status_active': "🟢 Активный — кто первый, тот и везёт!",
        'order_status_active_short': "🟢 Активный",
        'order_status_delivering': "🟡 В пути (Везёт: {courier})",
        'order_status_closed': "🔴 Закрыто ({time}, {courier} - {pay_icon})",
        'order_label': "ЗАКАЗ",
        'order_label_free': "СВОБОДНЫЙ ЗАКАЗ",
        'order_label_new': "НОВЫЙ ЗАКАЗ",
        'order_label_no_courier': "(без курьера)",
        'order_status_lbl': "Статус",
        'order_address_lbl': "Адрес",
        'order_details_lbl': "Детали",
        'order_client_lbl': "Клиент",
        'order_tel_lbl': "Тел",
        'order_comment_lbl': "Комментарий",
        'order_pay_cash_line': "💵 Наличные: {amount} {cur}",
        'order_pay_terminal_line': "🏧 Терминал: {amount} {cur}",
        'order_pay_online_line': "💳 Оплата: ОНЛАЙН (Оплачено)",
        'btn_take_order': "✅ Взять заказ",
        'btn_call': "📞 Позвонить",
        'btn_close_online': "✅ Закрыть (Онлайн оплачено)",
        'btn_close_cash': "💵 Наличные — {amount} {cur}",
        'btn_close_terminal': "🏧 Терминал — {amount} {cur}",
        'closing_order': "✅ Закрываем заказ...",
        'order_not_found': "❌ Заказ не найден.",
        'order_format_error': "❌ Ошибка формата callback.",
        'order_already_closed': "✅ Заказ уже закрыт.",
        'order_wrong_courier': "⛔️ Этот заказ ведёт другой курьер.",
        'courier_not_in_staff': "⛔️ Курьер не найден в персонале этого заведения.",
        'free_order_manager_notify': "📦 <b>НОВЫЙ ЗАКАЗ #{short_id}</b> (без курьера)\n\n📍 <b>Адрес:</b> {address}\n👤 <b>Клиент:</b> {client_name}\n📞 <b>Тел:</b> {phone}\n💰 <b>Сумма:</b> {amount} {cur}\n⚠️ Назначьте курьера через карту заказов.",
        'courier_returns': "🏠 Курьер возвращается на базу.",
        'courier_free': "✅ Курьер __свободен__ для работы.",
        'report_courier_line': "👤 {name}: {count} зак.",
        'report_online_line': " | 🌐 {count} онл. ({sum})",
        'report_online_summary': "\n🌐 Онлайн: {count} заказов | {sum} {cur} (оплачено)",
        'generic_error': "❌ Ошибка: {error}",
        'ticket_sent': "✅ <b>Тикет успешно отправлен!</b> Наша служба поддержки свяжется с вами в ближайшее время.",
        'ticket_admin_msg': "🆘 <b>НОВЫЙ ТИКЕТ ПОДДЕРЖКИ</b>\n\n🏢 <b>Бизнес ID:</b> <code>{biz_id}</code>\n👤 <b>От:</b> <a href='tg://user?id={user_id}'>Клиент (ID: {user_id})</a>\n🏷 <b>Категория:</b> {reason}\n📌 <b>Тема:</b> {topic}\n〰️〰️〰️〰️〰️〰️〰️〰️\n💬 <b>Сообщение:</b>\n<i>{message}</i>",
        'btn_call_regular': "📞 Позвонить",
        'btn_assign_courier': "🛵 Назначить курьера",
        'pos_order_new': "🔥 <b>НОВЫЙ ЗАКАЗ С {source}!</b>\n\n👤 <b>Клиент:</b> {client}\n📞 <b>Телефон:</b> {phone}\n📍 <b>Адрес:</b> {address}\n💰 <b>Сумма:</b> {amount} {cur}",
        'pos_order_comment': "\n💬 <b>Комментарий:</b> <i>{comment}</i>",
        'pro_activated': "🎉 <b>Поздравляем! Оплата прошла успешно!</b>\nТариф <b>PRO</b> активирован. Спасибо за доверие! 🚀",
        'subscription_expired': "⚠️ <b>Ваша подписка отменена.</b>\nДля возобновления откройте Дашборд.",
        'name_invalid': "⚠️ Имя должно быть от 2 до 50 символов и не начинаться с /",
        'btn_my_active_orders': "📦 Мои заказы",
        'client_default': "Клиент",
        # --- СМЕНА КУРЬЕРА ---
        'btn_start_shift': "🟢 Начать смену",
        'btn_close_shift': "🔴 Закрыть смену",
        'shift_already_active': "⚠️ У вас уже есть активная смена. Сначала закройте её.",
        'shift_send_start_photo': "📸 Сделайте фото спидометра перед началом смены и отправьте его сюда.",
        'shift_send_start_km': "✅ Фото получено!\n\nТеперь введите текущий километраж числом (например: <b>12340</b>):",
        'shift_started': "✅ Смена начата!\n\n🛣 Километраж <b>{name}</b> на начало смены: <b>{km} км</b>\n\nУдачи на маршруте! 🚀",
        'shift_photo_forwarded': "📸 <b>Фото спидометра — начало смены</b>\n👤 Курьер: <b>{name}</b>\n🛣 Км: <b>{km}</b>",
        'shift_notify_start': "🟢 Курьер <b>{name}</b> начал смену\n🛣 Км: <b>{km}</b>",
        'shift_notify_end': "🔴 Курьер <b>{name}</b> завершил смену\n🛣 Км: <b>{km}</b>",
        'shift_end_photo_forwarded': "📸 <b>Фото спидометра — конец смены</b>\n👤 Курьер: <b>{name}</b>\n🛣 Км: <b>{km}</b>",
        'shift_no_active': "⚠️ У вас нет активной смены. Сначала начните смену.",
        'shift_send_end_photo': "📸 Отправьте фото спидометра для закрытия смены.",
        'shift_send_end_km': "✅ Фото получено!\n\nВведите текущий километраж числом:",
        'shift_km_invalid': "❌ Неверный формат. Введите целое число, например: <b>12500</b>",
        'shift_km_less_than_start': "❌ Конечный километраж не может быть меньше начального (<b>{start_km} км</b>). Попробуйте ещё раз.",
        'shift_report': (
            "📊 <b>Отчёт за смену — {name}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "🛣 Километраж за смену: <b>{km} км</b>\n"
            "📦 Заказов: <b>{orders}</b>\n"
            "💵 Наличные: <b>{cash} {cur}</b>\n"
            "💳 Терминал: <b>{term} {cur}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "🚗 К оплате за км: <b>{km} × {rate} = {km_total} {cur}</b>\n"
            "🏦 Сдать в кассу: <b>{cash} − {km_total} = {to_pay} {cur}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "✅ Смена закрыта. Хорошего отдыха! 🏠"
        ),
        'shift_admin_report_header': "📊 <b>ОТЧЁТ СМЕН — {date}</b>\n➖➖➖➖➖➖➖➖➖\n",
        'shift_admin_report_line': (
            "👤 <b>{name}</b>\n"
            "  🛣 Км: {km} | 📦 Зак: {orders} | 💵 {cash} / 💳 {term} {cur}\n"
            "  🚗 За км: {km_total} {cur} | 🏦 В кассу: {to_pay} {cur}\n\n"
        ),
        'shift_admin_report_empty': "📭 Сегодня ещё нет закрытых смен.",
        'btn_shift_view_photo': "📸 Фото ({name})",
        'shift_photo_start_caption': "📸 Начало смены — {name}\n🛣 {km} км",
        'shift_photo_end_caption': "📸 Конец смены — {name}\n🛣 {km} км",
        'shift_photo_not_found': "❌ Фото не найдено.",
        'btn_shift_report': "📋 Отчёт смен",
        'start_menu_hint': "Нажмите /start чтобы открыть меню.",
        'order_taken_by_other': "⚠️ Этот заказ уже взят другим курьером.",
        'order_take_failed': "⚠️ Не удалось взять заказ. Попробуйте ещё раз.",
        'late_header': "🚨 ОПОЗДАНИЕ ЗАКАЗА!",
        'late_order_lbl': "Заказ",
        'late_addr_lbl': "Адрес",
        'late_phone_lbl': "Тел",
        'late_courier_lbl': "Курьер",
        'late_mins_msg': "Опоздание уже на {mins} мин!",
        'shift_on_duty': "🟢 <b>Сейчас на смене:</b>",
        'btn_photo_start': "📸 {name} — начало",
        'btn_photo_end': "📸 {name} — конец",
        'courier_since': "с {time} · {orders} зак.",
        }, 'pl': {
        'sub_expired': "⚠️ **Twoja subskrypcja wygasła lub została zawieszona.**\nProszę skontaktować się z administratorem.",
        'owner_panel': "🏢 **Panel właściciela: {name}**",
        'manager_panel': "👨‍💼 **Panel menedżera: {name}**",
        'courier_panel': "🛵 **Miejsce pracy kuriera: {name}**",
        'no_zvit_access': "❌ Nie masz dostępu do raportów.",
        'no_access': "⛔️ Nie masz uprawnień do tej akcji.",
        'zvit_empty': "📭 Dzisiaj nie ma jeszcze dostarczonych zamówień do raportu.",
        'zvit_title': "📊 RAPORT ({time})\n➖ ➖ ➖ ➖ ➖\n",
        'zvit_cash': "💰 Gotówka: {cash} {cur}\n",
        'zvit_term': "💳 Terminal: {term} {cur}",
        'boss_panel': "Witaj Szefie! 🫡\nOto dostęp do zarządzania wszystkimi firmami:",
        'dont_understand': "Nie rozumiem Cię 🤷‍♂️",
        'link_invalid': "🛑 Ten link jest nieważny, wygasł lub został anulowany przez właściciela!",
        'link_error': "❌ Wystąpił błąd podczas sprawdzania linku. Spróbuj ponownie później.",
        'role_c_full': "Kuriera 🛵",
        'role_m_full': "Menedżera 👨‍💼",
        'invite_welcome': "👋 Witamy!\nOtrzymałeś zaproszenie na stanowisko **{role}** w lokalu **{biz_name}**.\n\n✏️ Wprowadź swoje Imię i Nazwisko, aby dołączyć do zespołu:",
        'start_welcome': "🌟 **Witamy w DelivePro!**\n\nEwolucja Twojej dostawy zaczyna się tutaj. Kliknij przycisk poniżej, aby skonfigurować swój biznes.",
        'biz_already_exists': "⚠️ Masz już zarejestrowany lokal. Jeśli chcesz zmienić ustawienia — otwórz panel sterowania.",
        'biz_created': "🎉 **Gratulacje! Twój biznes '{biz_name}' został pomyślnie utworzony.**\n📦 **Plan:** {plan} (Aktywowano 7 dni okresu próbnego)\n\nTeraz możesz przejść do pełnego zarządzania 👇",
        'reg_error': "❌ Wystąpił błąd podczas rejestracji.",
        'pay_cash': "Gotówka",
        'pay_terminal': "Terminal",
        'pay_online': "Online",
        'apt_prefix': "Mieszk/Biuro: {apt}",
        'code_prefix': "Domofon: {code}",
        'details_prefix': "🏢 Szczegóły: {details}\n",
        'status_active_full': "Status: 🟢 Aktywny",
        'status_done_full': "Status: ✅ DOSTARCZONO",
        'order_new': "📦 **NOWE ZAMÓWIENIE #{short_id}**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n{status}\n\n📍 **Adres:** {address}\n{details_text}📞 **Tel:** {phone} ({client_name})\n{pay_icon} **Płatność:** {amount} {cur} ({pay_type})\n",
        'comment_prefix': "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n🗣 **Komentarz:** {comment}\n",
        'btn_route': "🗺 Otwórz trasę",
        'btn_finish': "✅ Dostarczono (Zamknij)",
        'order_sent': "✅ Zamówienie #{short_id} zostało pomyślnie utworzone i wysłane kurierowi!",
        'order_save_err': "❌ Błąd zapisywania zamówienia w bazie.",
        'order_send_err': "❌ Wystąpił błąd podczas wysyłania zamówienia.",
        'broadcast_no_access': "❌ Nie masz uprawnień do wysyłania wiadomości masowych.",
        'broadcast_empty': "📭 Brak właścicieli do wysłania wiadomości.",
        'broadcast_start': "🚀 Rozpoczynam wysyłanie do {count} klientów. Proszę czekać...",
        'broadcast_msg': "🔔 **Wiadomość z platformy:**\n\n{text}",
        'broadcast_done': "✅ Wysyłka pomyślnie zakończona!\nDostarczono: **{sent} z {total}** użytkowników.",
        'role_c': "Kurier",
        'role_m': "Menedżer",
        'staff_added': "✅ Witamy, {name}! Pomyślnie dołączyłeś do zespołu jako {role}.",
        'staff_add_err': "❌ Błąd dodawania. Spróbuj ponownie.",
        'already_registered': "✅ Jesteś już zarejestrowany/-a jako {role} w tym miejscu.",
        'finish_success': "🎉 Zamówienie pomyślnie zakończone! Pieniądze w kasie.",
        'finish_notify': "✅ **Zamówienie dostarczone!**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n📦 Numer: `#{short_id}`\n💰 Kwota: {amount} {cur}\n🛵 Kurier: {courier_name}\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n🏠 Kurier wraca do bazy.",
        'finish_err': "❌ Błąd zakończenia",
        'sa_empty': "📭 Na razie brak firm.",
        'sa_manage': "🚀 Zarządzanie SaaS:",
        'sa_changed': "Status zmieniony!",
        'btn_open_app': "🚀 Otwórz DelivePro",
        'btn_dashboard': "📊 Panel",
        'btn_map': "🗺 Mapa zamówień",
        'btn_report': "📊 Zrób raport",
        'btn_settings': "⚙️ Ustawienia firmy",
        'btn_staff': "👥 Personel",
        'btn_new_order': "📝 Nowe zamówienie",
        'btn_active_orders': "📂 Aktywne zamówienia",
        'btn_schedule': "📅 Harmonogram pracy",
        'btn_my_deliveries': "📦 Moje dostawy",
        'btn_boss_panel': "👑 Panel Właściciela",
        'expired_trial_text': "⚠️ **Twój okres próbny lub subskrypcja wygasła!**\n\nAby kontynuować pracę, proszę otworzyć Panel.",
        'expired_staff_text': "⚠️ **Subskrypcja lokalu wygasła.**\n\nSkontaktuj się z właścicielem w celu odnowienia.",
        'btn_open_dashboard': "📊 Otwórz Panel",
        'expired_no_orders': "⚠️ Subskrypcja wygasła. Nie możesz tworzyć nowych zamówień. Otwórz Panel.",
        'free_order_created': "🟢 **WOLNE ZAMÓWIENIE #{short_id}**\n\nZamówienie dodane na mapę! Otwórz mapę, aby przypisać kuriera.\n🔗 *Link do śledzenia dla klienta:*\n`{tracking_link}`",
        'order_assigned_success': "✅ Zamówienie #{short_id} pomyślnie przypisane!",
        'order_assign_error': "❌ Błąd podczas przypisywania zamówienia.",
        'order_already_assigned': "⚠️ To zamówienie zostało już przypisane kurierowi.",
        'expired_no_report': "⚠️ Subskrypcja wygasła. Otwórz Panel, aby dokonać płatności.",
        'tracking_link_label': "🔗 *Link do śledzenia dla klienta:*\n`{tracking_link}`",
        'order_status_active': "🟢 Aktywny — kto pierwszy, ten wiezie!",
        'order_status_active_short': "🟢 Aktywny",
        'order_status_delivering': "🟡 W drodze (Wiezie: {courier})",
        'order_status_closed': "🔴 Zamknięto ({time}, {courier} - {pay_icon})",
        'order_label': "ZAMÓWIENIE",
        'order_label_free': "WOLNE ZAMÓWIENIE",
        'order_label_new': "NOWE ZAMÓWIENIE",
        'order_label_no_courier': "(bez kuriera)",
        'order_status_lbl': "Status",
        'order_address_lbl': "Adres",
        'order_details_lbl': "Szczegóły",
        'order_client_lbl': "Klient",
        'order_tel_lbl': "Tel",
        'order_comment_lbl': "Komentarz",
        'order_pay_cash_line': "💵 Gotówka: {amount} {cur}",
        'order_pay_terminal_line': "🏧 Terminal: {amount} {cur}",
        'order_pay_online_line': "💳 Płatność: ONLINE (Opłacono)",
        'btn_take_order': "✅ Weź zamówienie",
        'btn_call': "📞 Zadzwoń",
        'btn_close_online': "✅ Zamknij (Online opłacono)",
        'btn_close_cash': "💵 Gotówka — {amount} {cur}",
        'btn_close_terminal': "🏧 Terminal — {amount} {cur}",
        'closing_order': "✅ Zamykamy zamówienie...",
        'order_not_found': "❌ Zamówienie nie znalezione.",
        'order_format_error': "❌ Błąd formatu callback.",
        'order_already_closed': "✅ Zamówienie już zamknięte.",
        'order_wrong_courier': "⛔️ To zamówienie prowadzi inny kurier.",
        'courier_not_in_staff': "⛔️ Kurier nie znaleziony w personelu tego lokalu.",
        'free_order_manager_notify': "📦 <b>NOWE ZAMÓWIENIE #{short_id}</b> (bez kuriera)\n\n📍 <b>Adres:</b> {address}\n👤 <b>Klient:</b> {client_name}\n📞 <b>Tel:</b> {phone}\n💰 <b>Kwota:</b> {amount} {cur}\n⚠️ Przypisz kuriera przez mapę zamówień.",
        'courier_returns': "🏠 Kurier wraca do bazy.",
        'courier_free': "✅ Kurier __wolny__ do pracy.",
        'report_courier_line': "👤 {name}: {count} zam.",
        'report_online_line': " | 🌐 {count} onl. ({sum})",
        'report_online_summary': "\n🌐 Online: {count} zamówień | {sum} {cur} (opłacono)",
        'generic_error': "❌ Błąd: {error}",
        'ticket_sent': "✅ <b>Zgłoszenie zostało wysłane!</b> Nasz dział wsparcia skontaktuje się z Tobą wkrótce.",
        'ticket_admin_msg': "🆘 <b>NOWE ZGŁOSZENIE WSPARCIA</b>\n\n🏢 <b>ID Firmy:</b> <code>{biz_id}</code>\n👤 <b>Od:</b> <a href='tg://user?id={user_id}'>Klient (ID: {user_id})</a>\n🏷 <b>Kategoria:</b> {reason}\n📌 <b>Temat:</b> {topic}\n〰️〰️〰️〰️〰️〰️〰️〰️\n💬 <b>Wiadomość:</b>\n<i>{message}</i>",
        'btn_call_regular': "📞 Zadzwoń",
        'btn_assign_courier': "🛵 Przypisz kuriera",
        'pos_order_new': "🔥 <b>NOWE ZAMÓWIENIE Z {source}!</b>\n\n👤 <b>Klient:</b> {client}\n📞 <b>Telefon:</b> {phone}\n📍 <b>Adres:</b> {address}\n💰 <b>Kwota:</b> {amount} {cur}",
        'pos_order_comment': "\n💬 <b>Komentarz:</b> <i>{comment}</i>",
        'pro_activated': "🎉 <b>Gratulacje! Płatność zakończona sukcesem!</b>\nPlan <b>PRO</b> aktywowany. Dziękujemy za zaufanie! 🚀",
        'subscription_expired': "⚠️ <b>Twoja subskrypcja została anulowana.</b>\nAby wznowić, otwórz Dashboard.",
        'name_invalid': "⚠️ Imię musi mieć od 2 do 50 znaków i nie może zaczynać się od /",
        'btn_my_active_orders': "📦 Moje zamówienia",
        'client_default': "Klient",
        # --- ZMIANA KURIERA ---
        'btn_start_shift': "🟢 Rozpocznij zmianę",
        'btn_close_shift': "🔴 Zakończ zmianę",
        'shift_already_active': "⚠️ Masz już aktywną zmianę. Najpierw ją zakończ.",
        'shift_send_start_photo': "📸 Zrób zdjęcie licznika przed rozpoczęciem zmiany i wyślij je tutaj.",
        'shift_send_start_km': "✅ Zdjęcie otrzymane!\n\nTeraz wprowadź aktualny przebieg liczbą (np: <b>12340</b>):",
        'shift_started': "✅ Zmiana rozpoczęta!\n\n🛣 Przebieg <b>{name}</b> na początku zmiany: <b>{km} km</b>\n\nPowodzenia na trasie! 🚀",
        'shift_photo_forwarded': "📸 <b>Zdjęcie licznika — początek zmiany</b>\n👤 Kurier: <b>{name}</b>\n🛣 Km: <b>{km}</b>",
        'shift_notify_start': "🟢 Kurier <b>{name}</b> rozpoczął zmianę\n🛣 Km: <b>{km}</b>",
        'shift_notify_end': "🔴 Kurier <b>{name}</b> zakończył zmianę\n🛣 Km: <b>{km}</b>",
        'shift_end_photo_forwarded': "📸 <b>Zdjęcie licznika — koniec zmiany</b>\n👤 Kurier: <b>{name}</b>\n🛣 Km: <b>{km}</b>",
        'shift_no_active': "⚠️ Nie masz aktywnej zmiany. Najpierw rozpocznij zmianę.",
        'shift_send_end_photo': "📸 Wyślij zdjęcie licznika, aby zakończyć zmianę.",
        'shift_send_end_km': "✅ Zdjęcie otrzymane!\n\nWprowadź aktualny przebieg liczbą:",
        'shift_km_invalid': "❌ Nieprawidłowy format. Wprowadź liczbę całkowitą, np: <b>12500</b>",
        'shift_km_less_than_start': "❌ Końcowy przebieg nie może być mniejszy niż początkowy (<b>{start_km} km</b>). Spróbuj ponownie.",
        'shift_report': (
            "📊 <b>Raport zmiany — {name}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "🛣 Przebieg: <b>{km} km</b>\n"
            "📦 Zamówień: <b>{orders}</b>\n"
            "💵 Gotówka: <b>{cash} {cur}</b>\n"
            "💳 Terminal: <b>{term} {cur}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "🚗 Do zapłaty za km: <b>{km} × {rate} = {km_total} {cur}</b>\n"
            "🏦 Do kasy: <b>{cash} − {km_total} = {to_pay} {cur}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "✅ Zmiana zakończona. Dobrego wypoczynku! 🏠"
        ),
        'shift_admin_report_header': "📊 <b>RAPORT ZMIAN — {date}</b>\n➖➖➖➖➖➖➖➖➖\n",
        'shift_admin_report_line': (
            "👤 <b>{name}</b>\n"
            "  🛣 Km: {km} | 📦 Zam: {orders} | 💵 {cash} / 💳 {term} {cur}\n"
            "  🚗 Za km: {km_total} {cur} | 🏦 Do kasy: {to_pay} {cur}\n\n"
        ),
        'shift_admin_report_empty': "📭 Dziś nie ma jeszcze zamkniętych zmian.",
        'btn_shift_view_photo': "📸 Zdjęcie ({name})",
        'shift_photo_start_caption': "📸 Początek zmiany — {name}\n🛣 {km} km",
        'shift_photo_end_caption': "📸 Koniec zmiany — {name}\n🛣 {km} km",
        'shift_photo_not_found': "❌ Zdjęcie nie znalezione.",
        'btn_shift_report': "📋 Raport zmian",
        'start_menu_hint': "Naciśnij /start aby otworzyć menu.",
        'order_taken_by_other': "⚠️ To zamówienie zostało już przejęte przez innego kuriera.",
        'order_take_failed': "⚠️ Nie udało się przejąć zamówienia. Spróbuj ponownie.",
        'late_header': "🚨 SPÓŹNIENIE ZAMÓWIENIA!",
        'late_order_lbl': "Zamówienie",
        'late_addr_lbl': "Adres",
        'late_phone_lbl': "Tel",
        'late_courier_lbl': "Kurier",
        'late_mins_msg': "Spóźnienie już o {mins} min!",
        'shift_on_duty': "🟢 <b>Teraz na zmianie:</b>",
        'btn_photo_start': "📸 {name} — początek",
        'btn_photo_end': "📸 {name} — koniec",
        'courier_since': "od {time} · {orders} zam.",
        }, 'en': {
        'sub_expired': "⚠️ **Your subscription has expired or been suspended.**\nPlease contact the administrator.",
        'owner_panel': "🏢 **Owner Panel: {name}**",
        'manager_panel': "👨‍💼 **Manager Panel: {name}**",
        'courier_panel': "🛵 **Courier Workspace: {name}**",
        'no_zvit_access': "❌ You do not have access to reports.",
        'no_access': "⛔️ You don't have permission for this action.",
        'zvit_empty': "📭 No delivered orders today for the report.",
        'zvit_title': "📊 REPORT ({time})\n➖ ➖ ➖ ➖ ➖\n",
        'zvit_cash': "💰 Cash: {cash} {cur}\n",
        'zvit_term': "💳 Terminal: {term} {cur}",
        'boss_panel': "Hello, Boss! 🫡\nHere is access to manage all businesses:",
        'dont_understand': "I do not understand you 🤷‍♂️",
        'link_invalid': "🛑 This link is invalid, expired, or was revoked by the owner!",
        'link_error': "❌ An error occurred while checking the link. Please try again later.",
        'role_c_full': "Courier 🛵",
        'role_m_full': "Manager 👨‍💼",
        'invite_welcome': "👋 Welcome!\nYou received an invitation for the role of **{role}** at **{biz_name}**.\n\n✏️ Enter your First and Last Name to join the team:",
        'start_welcome': "🌟 **Welcome to DelivePro!**\n\nThe evolution of your delivery starts here. Click the button below to set up your business.",
        'biz_already_exists': "⚠️ You already have a registered business. To change settings — open the control panel.",
        'biz_created': "🎉 **Congratulations! Your business '{biz_name}' has been successfully created.**\n📦 **Plan:** {plan} (7-day trial activated)\n\nNow you can proceed to full management 👇",
        'reg_error': "❌ An error occurred during registration.",
        'pay_cash': "Cash",
        'pay_terminal': "Terminal",
        'pay_online': "Online",
        'apt_prefix': "Apt/Office: {apt}",
        'code_prefix': "Intercom: {code}",
        'details_prefix': "🏢 Details: {details}\n",
        'status_active_full': "Status: 🟢 Active",
        'status_done_full': "Status: ✅ DELIVERED",
        'order_new': "📦 **NEW ORDER #{short_id}**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n{status}\n\n📍 **Address:** {address}\n{details_text}📞 **Tel:** {phone} ({client_name})\n{pay_icon} **Payment:** {amount} {cur} ({pay_type})\n",
        'comment_prefix': "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n🗣 **Comment:** {comment}\n",
        'btn_route': "🗺 Open Route",
        'btn_finish': "✅ Delivered (Close)",
        'order_sent': "✅ Order #{short_id} successfully created and sent to courier!",
        'order_save_err': "❌ Error saving the order to the database.",
        'order_send_err': "❌ An error occurred while sending the order.",
        'broadcast_no_access': "❌ You don't have permission to broadcast.",
        'broadcast_empty': "📭 No owners found for broadcast.",
        'broadcast_start': "🚀 Starting broadcast to {count} clients. Please wait...",
        'broadcast_msg': "🔔 **Message from platform:**\n\n{text}",
        'broadcast_done': "✅ Broadcast successfully completed!\nDelivered: **{sent} of {total}** users.",
        'role_c': "Courier",
        'role_m': "Manager",
        'staff_added': "✅ Welcome, {name}! You successfully joined the team as {role}.",
        'staff_add_err': "❌ Error adding staff. Please try again.",
        'already_registered': "✅ You are already registered as {role} at this place.",
        'finish_success': "🎉 Order successfully completed! Money in the register.",
        'finish_notify': "🔔 **Order delivered!**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n📦 Number: `#{short_id}`\n💰 Amount: {amount} {cur}\n🛵 Courier: {courier_name}\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n✅ Courier is __free__ for work again.",
        'finish_err': "❌ Completion error",
        'sa_empty': "📭 No businesses yet.",
        'sa_manage': "🚀 SaaS Management:",
        'sa_changed': "Status changed!",
        'btn_open_app': "🚀 Open DelivePro",
        'btn_dashboard': "📊 Dashboard",
        'btn_map': "🗺 Orders Map",
        'btn_report': "📊 Make Report",
        'btn_settings': "⚙️ Business Settings",
        'btn_staff': "👥 Staff",
        'btn_new_order': "📝 New Order",
        'btn_active_orders': "📂 Active Orders",
        'btn_schedule': "📅 Work Schedule",
        'btn_my_deliveries': "📦 My Deliveries",
        'btn_boss_panel': "👑 Boss Panel",
        'expired_trial_text': "⚠️ **Your trial period or subscription has expired!**\n\nTo continue working, please open the Dashboard.",
        'expired_staff_text': "⚠️ **The venue subscription has expired.**\n\nPlease contact the owner to renew.",
        'btn_open_dashboard': "📊 Open Dashboard",
        'expired_no_orders': "⚠️ Subscription expired. You cannot create new orders. Please open the Dashboard.",
        'free_order_created': "🟢 **FREE ORDER #{short_id}**\n\nOrder added to the map! Open the map to assign a courier.\n🔗 *Tracking link for client:*\n`{tracking_link}`",
        'order_assigned_success': "✅ Order #{short_id} successfully assigned!",
        'order_assign_error': "❌ Error assigning the order.",
        'order_already_assigned': "⚠️ This order has already been assigned to a courier.",
        'expired_no_report': "⚠️ Subscription expired. Please open the Dashboard to pay.",
        'tracking_link_label': "🔗 *Tracking link for client:*\n`{tracking_link}`",
        'order_status_active': "🟢 Active — first come, first serve!",
        'order_status_active_short': "🟢 Active",
        'order_status_delivering': "🟡 On the way (Courier: {courier})",
        'order_status_closed': "🔴 Closed ({time}, {courier} - {pay_icon})",
        'order_label': "ORDER",
        'order_label_free': "FREE ORDER",
        'order_label_new': "NEW ORDER",
        'order_label_no_courier': "(no courier)",
        'order_status_lbl': "Status",
        'order_address_lbl': "Address",
        'order_details_lbl': "Details",
        'order_client_lbl': "Client",
        'order_tel_lbl': "Tel",
        'order_comment_lbl': "Comment",
        'order_pay_cash_line': "💵 Cash: {amount} {cur}",
        'order_pay_terminal_line': "🏧 Terminal: {amount} {cur}",
        'order_pay_online_line': "💳 Payment: ONLINE (Paid)",
        'btn_take_order': "✅ Take order",
        'btn_call': "📞 Call",
        'btn_close_online': "✅ Close (Online paid)",
        'btn_close_cash': "💵 Cash — {amount} {cur}",
        'btn_close_terminal': "🏧 Terminal — {amount} {cur}",
        'closing_order': "✅ Closing order...",
        'order_not_found': "❌ Order not found.",
        'order_format_error': "❌ Callback format error.",
        'order_already_closed': "✅ Order already closed.",
        'order_wrong_courier': "⛔️ This order is being handled by another courier.",
        'courier_not_in_staff': "⛔️ Courier not found in this venue's staff.",
        'free_order_manager_notify': "📦 <b>NEW ORDER #{short_id}</b> (no courier)\n\n📍 <b>Address:</b> {address}\n👤 <b>Client:</b> {client_name}\n📞 <b>Tel:</b> {phone}\n💰 <b>Amount:</b> {amount} {cur}\n⚠️ Assign a courier via the orders map.",
        'courier_returns': "🏠 Courier is returning to base.",
        'courier_free': "✅ Courier is __free__ for work again.",
        'report_courier_line': "👤 {name}: {count} ord.",
        'report_online_line': " | 🌐 {count} onl. ({sum})",
        'report_online_summary': "\n🌐 Online: {count} orders | {sum} {cur} (paid)",
        'generic_error': "❌ Error: {error}",
        'ticket_sent': "✅ <b>Ticket sent successfully!</b> Our support team will contact you shortly.",
        'ticket_admin_msg': "🆘 <b>NEW SUPPORT TICKET</b>\n\n🏢 <b>Business ID:</b> <code>{biz_id}</code>\n👤 <b>From:</b> <a href='tg://user?id={user_id}'>Client (ID: {user_id})</a>\n🏷 <b>Category:</b> {reason}\n📌 <b>Topic:</b> {topic}\n〰️〰️〰️〰️〰️〰️〰️〰️\n💬 <b>Message:</b>\n<i>{message}</i>",
        'btn_call_regular': "📞 Call",
        'btn_assign_courier': "🛵 Assign Courier",
        'pos_order_new': "🔥 <b>NEW ORDER FROM {source}!</b>\n\n👤 <b>Client:</b> {client}\n📞 <b>Phone:</b> {phone}\n📍 <b>Address:</b> {address}\n💰 <b>Amount:</b> {amount} {cur}",
        'pos_order_comment': "\n💬 <b>Comment:</b> <i>{comment}</i>",
        'pro_activated': "🎉 <b>Congratulations! Payment successful!</b>\n<b>PRO</b> plan activated. Thank you for your trust! 🚀",
        'subscription_expired': "⚠️ <b>Your subscription has been cancelled.</b>\nOpen the Dashboard to renew.",
        'name_invalid': "⚠️ Name must be 2–50 characters and cannot start with /",
        'btn_my_active_orders': "📦 My Orders",
        'client_default': "Client",
        # --- COURIER SHIFT ---
        'btn_start_shift': "🟢 Start Shift",
        'btn_close_shift': "🔴 End Shift",
        'shift_already_active': "⚠️ You already have an active shift. Please close it first.",
        'shift_send_start_photo': "📸 Take a photo of the odometer before starting your shift and send it here.",
        'shift_send_start_km': "✅ Photo received!\n\nNow enter the current mileage as a number (e.g. <b>12340</b>):",
        'shift_started': "✅ Shift started!\n\n🛣 Mileage for <b>{name}</b> at shift start: <b>{km} km</b>\n\nGood luck on the road! 🚀",
        'shift_photo_forwarded': "📸 <b>Odometer photo — shift start</b>\n👤 Courier: <b>{name}</b>\n🛣 Km: <b>{km}</b>",
        'shift_notify_start': "🟢 Courier <b>{name}</b> started a shift\n🛣 Km: <b>{km}</b>",
        'shift_notify_end': "🔴 Courier <b>{name}</b> ended a shift\n🛣 Km: <b>{km}</b>",
        'shift_end_photo_forwarded': "📸 <b>Odometer photo — shift end</b>\n👤 Courier: <b>{name}</b>\n🛣 Km: <b>{km}</b>",
        'shift_no_active': "⚠️ You have no active shift. Please start a shift first.",
        'shift_send_end_photo': "📸 Send a photo of the odometer to close your shift.",
        'shift_send_end_km': "✅ Photo received!\n\nEnter the current mileage as a number:",
        'shift_km_invalid': "❌ Invalid format. Enter a whole number, e.g. <b>12500</b>",
        'shift_km_less_than_start': "❌ End mileage cannot be less than start mileage (<b>{start_km} km</b>). Try again.",
        'shift_report': (
            "📊 <b>Shift Report — {name}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "🛣 Mileage: <b>{km} km</b>\n"
            "📦 Orders: <b>{orders}</b>\n"
            "💵 Cash: <b>{cash} {cur}</b>\n"
            "💳 Terminal: <b>{term} {cur}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "🚗 To pay for km: <b>{km} × {rate} = {km_total} {cur}</b>\n"
            "🏦 To hand to cashier: <b>{cash} − {km_total} = {to_pay} {cur}</b>\n"
            "➖➖➖➖➖➖➖➖➖\n"
            "✅ Shift closed. Have a good rest! 🏠"
        ),
        'shift_admin_report_header': "📊 <b>SHIFT REPORT — {date}</b>\n➖➖➖➖➖➖➖➖➖\n",
        'shift_admin_report_line': (
            "👤 <b>{name}</b>\n"
            "  🛣 Km: {km} | 📦 Ord: {orders} | 💵 {cash} / 💳 {term} {cur}\n"
            "  🚗 For km: {km_total} {cur} | 🏦 To cashier: {to_pay} {cur}\n\n"
        ),
        'shift_admin_report_empty': "📭 No closed shifts today yet.",
        'btn_shift_view_photo': "📸 Photo ({name})",
        'shift_photo_start_caption': "📸 Shift start — {name}\n🛣 {km} km",
        'shift_photo_end_caption': "📸 Shift end — {name}\n🛣 {km} km",
        'shift_photo_not_found': "❌ Photo not found.",
        'btn_shift_report': "📋 Shift Report",
        'start_menu_hint': "Press /start to open the menu.",
        'order_taken_by_other': "⚠️ This order has already been taken by another courier.",
        'order_take_failed': "⚠️ Failed to take the order. Please try again.",
        'late_header': "🚨 ORDER LATE!",
        'late_order_lbl': "Order",
        'late_addr_lbl': "Address",
        'late_phone_lbl': "Phone",
        'late_courier_lbl': "Courier",
        'late_mins_msg': "Already {mins} min late!",
        'shift_on_duty': "Currently on shift:",
        'btn_photo_start': "Photo {name} - start",
        'btn_photo_end': "Photo {name} - end",
        'courier_since': "since {time} - {orders} ord.",
   }
}
def get_text(lang_code: str, key: str, **kwargs) -> str:
    """Отримує переклад з TEXTS. Якщо мови нема - бере англійську. Дозволяє форматування."""
    code = (lang_code or 'en').split('-')[0].lower()
    lang = code if code in TEXTS else 'en'
    text = TEXTS[lang].get(key, TEXTS['en'].get(key, key))
    if kwargs:
        return text.format(**kwargs)
    return text
