# texts.py

TEXTS = {
    'uk': {
        'sub_expired': "⚠️ **Ваша підписка закінчилася або призупинена.**\nБудь ласка, зверніться до адміністратора.",
        'owner_panel': "🏢 **Кабінет власника: {name}**",
        'manager_panel': "👨‍💼 **Панель менеджера: {name}**",
        'courier_panel': "🛵 **Робоче місце кур'єра: {name}**",
        'no_zvit_access': "❌ У вас немає доступу до звітів.",
        'zvit_empty': "📭 Сьогодні ще немає доставлених замовлень для звіту.",
        'zvit_title': "📊 ЗВІТ ({time})\n➖ ➖ ➖ ➖ ➖\n",
        'zvit_cash': "💰 Готівка: {cash} {cur}\n",
        'zvit_term': "💳 Термінал: {term} {cur}",
        'boss_panel': "Вітаю, Бос! 🫡\nОсь доступ до керування всіма бізнесами:",
        'dont_understand': "Я вас не розумію 🤷‍♂️",
        'link_invalid': "🛑 Це посилання недійсне, застаріло або було анульоване власником!",
        'link_error': "❌ Сталася помилка при перевірці посилання. Спробуйте пізніше.",
        'role_c_full': "Кур'єра 🛵",
        'role_m_full': "Менеджера 👨‍💼",
        'invite_welcome': "👋 Вітаємо!\nВи отримали запрошення на посаду **{role}** у заклад **{biz_name}**.\n\n✏️ Введіть ваше Прізвище та Ім'я, щоб приєднатися до команди:",
        'start_welcome': "🌟 **Вітаємо в DelivePro!**\n\nЕволюція вашої доставки починається тут. Натисніть кнопку нижче, щоб налаштувати свій бізнес.",
        'biz_created': "🎉 **Вітаємо! Ваш бізнес '{biz_name}' успішно створено.**\n📦 **Тариф:** {plan} (Активовано 7 днів тріалу)\n\nТепер ви можете перейти до повноцінного керування 👇",
        'reg_error': "❌ Сталася помилка при реєстрації. Перевірте логи.",
        'pay_cash': "Готівка",
        'pay_terminal': "Термінал",
        'pay_online': "Онлайн",
        'apt_prefix': "Кв/Оф: {apt}",
        'code_prefix': "Домофон: {code}",
        'details_prefix': "🏢 **Деталі:** {details}\n",
        'status_active_full': "Статус: 🟢 Активний",
        'status_done_full': "Статус: ✅ ДОСТАВЛЕНО",
        'order_new': "📦 **НОВЕ ЗАМОВЛЕННЯ #{short_id}**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n{status}\n\n📍 **Адреса:** {address}\n{details_text}📞 **Тел:** {phone} ({client_name})\n{pay_icon} **Оплата:** {amount} {cur} ({pay_type})\n",
        'comment_prefix': "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n🗣 **Коментар:** {comment}\n",
        'btn_route': "🗺 Відкрити маршрут",
        'btn_finish': "✅ Доставлено (Закрити)",
        'order_sent': "✅ Замовлення #{short_id} успішно створено та відправлено кур'єру!",
        'order_save_err': "❌ Помилка при збереженні замовлення в базу.",
        'order_send_err': "❌ Сталася помилка при відправці замовлення.",
        'broadcast_no_access': "❌ У вас немає прав для розсилки.",
        'broadcast_empty': "📭 Немає жодного власника для розсилки.",
        'broadcast_start': "🚀 Починаю розсилку для {count} клієнтів. Зачекайте...",
        'broadcast_msg': "🔔 **Повідомлення від платформи:**\n\n{text}",
        'broadcast_done': "✅ Розсилка успішно завершена!\nДоставлено: **{sent} з {total}** користувачів.",
        'role_c': "Кур'єр",
        'role_m': "Менеджер",
        'staff_added': "✅ Вітаємо, {name}! Ви успішно приєдналися до команди як {role}.",
        'staff_add_err': "❌ Помилка при додаванні. Можливо, ви вже працюєте тут.",
        'finish_success': "🎉 Замовлення успішно завершено! Гроші в касі.",
        'finish_notify': "🔔 **Замовлення доставлено!**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n📦 Номер: `#{short_id}`\n💰 Сума: {amount} {cur}\n🛵 Кур'єр: {courier_name}\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n✅ Кур'єр знову **вільний** для роботи.",
        'finish_err': "❌ Помилка завершення",
        'sa_empty': "📭 Бізнесів поки немає.",
        'sa_manage': "🚀 Керування SaaS:",
        'sa_changed': "Статус змінено!",
        
        # --- КНОПКИ КЛАВІАТУР (НОВЕ) ---
        'btn_open_app': "🚀 Відкрити DelivePro",
        'btn_dashboard': "📊 Дашборд",
        'btn_map': "🗺 Карта замовлень",
        'btn_report': "📊 Зробити звіт",
        'btn_settings': "⚙️ Налаштування бізнесу",
        'btn_staff': "👥 Персонал",
        'btn_new_order': "📝 Нове замовлення",
        'btn_active_orders': "📂 Активні замовлення",
        'btn_my_deliveries': "📦 Мої доставки",
        'btn_boss_panel': "👑 Панель Власника"
    },
    'ru': {
        'sub_expired': "⚠️ **Ваша подписка закончилась или приостановлена.**\nПожалуйста, обратитесь к администратору.",
        'owner_panel': "🏢 **Кабинет владельца: {name}**",
        'manager_panel': "👨‍💼 **Панель менеджера: {name}**",
        'courier_panel': "🛵 **Рабочее место курьера: {name}**",
        'no_zvit_access': "❌ У вас нет доступа к отчетам.",
        'zvit_empty': "📭 Сегодня еще нет доставленных заказов для отчета.",
        'zvit_title': "📊 ОТЧЕТ ({time})\n➖ ➖ ➖ ➖ ➖\n",
        'zvit_cash': "💰 Наличные: {cash} {cur}\n",
        'zvit_term': "💳 Терминал: {term} {cur}",
        'boss_panel': "Привет, Босс! 🫡\nВот доступ к управлению всеми бизнесами:",
        'dont_understand': "Я вас не понимаю 🤷‍♂️",
        'link_invalid': "🛑 Эта ссылка недействительна, устарела или была аннулирована владельцем!",
        'link_error': "❌ Произошла ошибка при проверке ссылки. Попробуйте позже.",
        'role_c_full': "Курьера 🛵",
        'role_m_full': "Менеджера 👨‍💼",
        'invite_welcome': "👋 Приветствуем!\nВы получили приглашение на должность **{role}** в заведение **{biz_name}**.\n\n✏️ Введите ваши Имя и Фамилию, чтобы присоединиться к команде:",
        'start_welcome': "🌟 **Добро пожаловать в DelivePro!**\n\nЭволюция вашей доставки начинается здесь. Нажмите кнопку ниже, чтобы настроить свой бизнес.",
        'biz_created': "🎉 **Поздравляем! Ваш бизнес '{biz_name}' успешно создан.**\n📦 **Тариф:** {plan} (Активировано 7 дней триала)\n\nТеперь вы можете перейти к полноценному управлению 👇",
        'reg_error': "❌ Произошла ошибка при регистрации.",
        'pay_cash': "Наличные",
        'pay_terminal': "Терминал",
        'pay_online': "Онлайн",
        'apt_prefix': "Кв/Оф: {apt}",
        'code_prefix': "Домофон: {code}",
        'details_prefix': "🏢 **Детали:** {details}\n",
        'status_active_full': "Статус: 🟢 Активный",
        'status_done_full': "Статус: ✅ ДОСТАВЛЕНО",
        'order_new': "📦 **НОВЫЙ ЗАКАЗ #{short_id}**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n{status}\n\n📍 **Адрес:** {address}\n{details_text}📞 **Тел:** {phone} ({client_name})\n{pay_icon} **Оплата:** {amount} {cur} ({pay_type})\n",
        'comment_prefix': "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n🗣 **Комментарий:** {comment}\n",
        'btn_route': "🗺 Открыть маршрут",
        'btn_finish': "✅ Доставлено (Закрыть)",
        'order_sent': "✅ Заказ #{short_id} успешно создан и отправлен курьеру!",
        'order_save_err': "❌ Ошибка при сохранении заказа в базу.",
        'order_send_err': "❌ Произошла ошибка при отправке заказа.",
        'broadcast_no_access': "❌ У вас нет прав для рассылки.",
        'broadcast_empty': "📭 Нет ни одного владельца для рассылки.",
        'broadcast_start': "🚀 Начинаю рассылку для {count} клиентов. Подождите...",
        'broadcast_msg': "🔔 **Сообщение от платформы:**\n\n{text}",
        'broadcast_done': "✅ Рассылка успешно завершена!\nДоставлено: **{sent} из {total}** пользователей.",
        'role_c': "Курьер",
        'role_m': "Менеджер",
        'staff_added': "✅ Поздравляем, {name}! Вы успешно присоединились к команде как {role}.",
        'staff_add_err': "❌ Ошибка при добавлении. Возможно, вы уже работаете здесь.",
        'finish_success': "🎉 Заказ успешно завершен! Деньги в кассе.",
        'finish_notify': "🔔 **Заказ доставлен!**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n📦 Номер: `#{short_id}`\n💰 Сумма: {amount} {cur}\n🛵 Курьер: {courier_name}\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n✅ Курьер снова **свободен** для работы.",
        'finish_err': "❌ Ошибка завершения",
        'sa_empty': "📭 Бизнесов пока нет.",
        'sa_manage': "🚀 Управление SaaS:",
        'sa_changed': "Статус изменен!",

        # --- КНОПКИ КЛАВІАТУР (НОВЕ) ---
        'btn_open_app': "🚀 Открыть DelivePro",
        'btn_dashboard': "📊 Дашборд",
        'btn_map': "🗺 Карта заказов",
        'btn_report': "📊 Сделать отчет",
        'btn_settings': "⚙️ Настройки бизнеса",
        'btn_staff': "👥 Персонал",
        'btn_new_order': "📝 Новый заказ",
        'btn_active_orders': "📂 Активные заказы",
        'btn_my_deliveries': "📦 Мои доставки",
        'btn_boss_panel': "👑 Панель Владельца"
    },
    'pl': {
        'sub_expired': "⚠️ **Twoja subskrypcja wygasła lub została zawieszona.**\nProszę skontaktować się z administratorem.",
        'owner_panel': "🏢 **Panel właściciela: {name}**",
        'manager_panel': "👨‍💼 **Panel menedżera: {name}**",
        'courier_panel': "🛵 **Miejsce pracy kuriera: {name}**",
        'no_zvit_access': "❌ Nie masz dostępu do raportów.",
        'zvit_empty': "📭 Dzisiaj nie ma jeszcze dostarczonych zamówień do raportu.",
        'zvit_title': "📊 RAPORT ({time})\n➖ ➖ ➖ ➖ ➖\n",
        'zvit_cash': "💰 Gotówka: {cash} {cur}\n",
        'zvit_term': "💳 Terminal: {term} {cur}",
        'boss_panel': "Witaj Szefie! 🫡\nOto dostęp do zarządzania wszystkimi firmami:",
        'dont_understand': "Nie rozumiem Cię 🤷‍♂️",
        'link_invalid': "🛑 Ten link jest nieważny, wygasł lub został anulowany przez właściciela!",
        'link_error': "❌ Wystąpił błąd podczas sprawdzania linku. Spróbuj ponownie później.",
        'role_c_full': "Kuriera 🛵",
        'role_m_full': "Menedżera 👨‍💼",
        'invite_welcome': "👋 Witamy!\nOtrzymałeś zaproszenie na stanowisko **{role}** w lokalu **{biz_name}**.\n\n✏️ Wprowadź swoje Imię i Nazwisko, aby dołączyć do zespołu:",
        'start_welcome': "🌟 **Witamy w DelivePro!**\n\nEwolucja Twojej dostawy zaczyna się tutaj. Kliknij przycisk poniżej, aby skonfigurować swój biznes.",
        'biz_created': "🎉 **Gratulacje! Twój biznes '{biz_name}' został pomyślnie utworzony.**\n📦 **Plan:** {plan} (Aktywowano 7 dni okresu próbnego)\n\nTeraz możesz przejść do pełnego zarządzania 👇",
        'reg_error': "❌ Wystąpił błąd podczas rejestracji.",
        'pay_cash': "Gotówka",
        'pay_terminal': "Terminal",
        'pay_online': "Online",
        'apt_prefix': "Mieszk/Biuro: {apt}",
        'code_prefix': "Domofon: {code}",
        'details_prefix': "🏢 **Szczegóły:** {details}\n",
        'status_active_full': "Status: 🟢 Aktywny",
        'status_done_full': "Status: ✅ DOSTARCZONO",
        'order_new': "📦 **NOWE ZAMÓWIENIE #{short_id}**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n{status}\n\n📍 **Adres:** {address}\n{details_text}📞 **Tel:** {phone} ({client_name})\n{pay_icon} **Płatność:** {amount} {cur} ({pay_type})\n",
        'comment_prefix': "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n🗣 **Komentarz:** {comment}\n",
        'btn_route': "🗺 Otwórz trasę",
        'btn_finish': "✅ Dostarczono (Zamknij)",
        'order_sent': "✅ Zamówienie #{short_id} zostało pomyślnie utworzone i wysłane kurierowi!",
        'order_save_err': "❌ Błąd zapisywania zamówienia w bazie.",
        'order_send_err': "❌ Wystąpił błąd podczas wysyłania zamówienia.",
        'broadcast_no_access': "❌ Nie masz uprawnień do wysyłania wiadomości masowych.",
        'broadcast_empty': "📭 Brak właścicieli do wysłania wiadomości.",
        'broadcast_start': "🚀 Rozpoczynam wysyłanie do {count} klientów. Proszę czekać...",
        'broadcast_msg': "🔔 **Wiadomość z platformy:**\n\n{text}",
        'broadcast_done': "✅ Wysyłka pomyślnie zakończona!\nDostarczono: **{sent} z {total}** użytkowników.",
        'role_c': "Kurier",
        'role_m': "Menedżer",
        'staff_added': "✅ Witamy, {name}! Pomyślnie dołączyłeś do zespołu jako {role}.",
        'staff_add_err': "❌ Błąd dodawania. Możliwe, że już tu pracujesz.",
        'finish_success': "🎉 Zamówienie pomyślnie zakończone! Pieniądze w kasie.",
        'finish_notify': "🔔 **Zamówienie dostarczone!**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n📦 Numer: `#{short_id}`\n💰 Kwota: {amount} {cur}\n🛵 Kurier: {courier_name}\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n✅ Kurier znów jest **wolny** do pracy.",
        'finish_err': "❌ Błąd zakończenia",
        'sa_empty': "📭 Na razie brak firm.",
        'sa_manage': "🚀 Zarządzanie SaaS:",
        'sa_changed': "Status zmieniony!",

        # --- КНОПКИ КЛАВІАТУР (НОВЕ) ---
        'btn_open_app': "🚀 Otwórz DelivePro",
        'btn_dashboard': "📊 Panel",
        'btn_map': "🗺 Mapa zamówień",
        'btn_report': "📊 Zrób raport",
        'btn_settings': "⚙️ Ustawienia firmy",
        'btn_staff': "👥 Personel",
        'btn_new_order': "📝 Nowe zamówienie",
        'btn_active_orders': "📂 Aktywne zamówienia",
        'btn_my_deliveries': "📦 Moje dostawy",
        'btn_boss_panel': "👑 Panel Właściciela"
    },
    'en': {
        'sub_expired': "⚠️ **Your subscription has expired or been suspended.**\nPlease contact the administrator.",
        'owner_panel': "🏢 **Owner Panel: {name}**",
        'manager_panel': "👨‍💼 **Manager Panel: {name}**",
        'courier_panel': "🛵 **Courier Workspace: {name}**",
        'no_zvit_access': "❌ You do not have access to reports.",
        'zvit_empty': "📭 No delivered orders today for the report.",
        'zvit_title': "📊 REPORT ({time})\n➖ ➖ ➖ ➖ ➖\n",
        'zvit_cash': "💰 Cash: {cash} {cur}\n",
        'zvit_term': "💳 Terminal: {term} {cur}",
        'boss_panel': "Hello, Boss! 🫡\nHere is access to manage all businesses:",
        'dont_understand': "I do not understand you 🤷‍♂️",
        'link_invalid': "🛑 This link is invalid, expired, or was revoked by the owner!",
        'link_error': "❌ An error occurred while checking the link. Please try again later.",
        'role_c_full': "Courier 🛵",
        'role_m_full': "Manager 👨‍💼",
        'invite_welcome': "👋 Welcome!\nYou received an invitation for the role of **{role}** at **{biz_name}**.\n\n✏️ Enter your First and Last Name to join the team:",
        'start_welcome': "🌟 **Welcome to DelivePro!**\n\nThe evolution of your delivery starts here. Click the button below to set up your business.",
        'biz_created': "🎉 **Congratulations! Your business '{biz_name}' has been successfully created.**\n📦 **Plan:** {plan} (7-day trial activated)\n\nNow you can proceed to full management 👇",
        'reg_error': "❌ An error occurred during registration.",
        'pay_cash': "Cash",
        'pay_terminal': "Terminal",
        'pay_online': "Online",
        'apt_prefix': "Apt/Office: {apt}",
        'code_prefix': "Intercom: {code}",
        'details_prefix': "🏢 **Details:** {details}\n",
        'status_active_full': "Status: 🟢 Active",
        'status_done_full': "Status: ✅ DELIVERED",
        'order_new': "📦 **NEW ORDER #{short_id}**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n{status}\n\n📍 **Address:** {address}\n{details_text}📞 **Tel:** {phone} ({client_name})\n{pay_icon} **Payment:** {amount} {cur} ({pay_type})\n",
        'comment_prefix': "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n🗣 **Comment:** {comment}\n",
        'btn_route': "🗺 Open Route",
        'btn_finish': "✅ Delivered (Close)",
        'order_sent': "✅ Order #{short_id} successfully created and sent to courier!",
        'order_save_err': "❌ Error saving the order to the database.",
        'order_send_err': "❌ An error occurred while sending the order.",
        'broadcast_no_access': "❌ You don't have permission to broadcast.",
        'broadcast_empty': "📭 No owners found for broadcast.",
        'broadcast_start': "🚀 Starting broadcast to {count} clients. Please wait...",
        'broadcast_msg': "🔔 **Message from platform:**\n\n{text}",
        'broadcast_done': "✅ Broadcast successfully completed!\nDelivered: **{sent} of {total}** users.",
        'role_c': "Courier",
        'role_m': "Manager",
        'staff_added': "✅ Welcome, {name}! You successfully joined the team as {role}.",
        'staff_add_err': "❌ Error adding. You might already be working here.",
        'finish_success': "🎉 Order successfully completed! Money in the register.",
        'finish_notify': "🔔 **Order delivered!**\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n📦 Number: `#{short_id}`\n💰 Amount: {amount} {cur}\n🛵 Courier: {courier_name}\n⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯\n✅ Courier is **free** for work again.",
        'finish_err': "❌ Completion error",
        'sa_empty': "📭 No businesses yet.",
        'sa_manage': "🚀 SaaS Management:",
        'sa_changed': "Status changed!",
        
        # --- КНОПКИ КЛАВІАТУР (НОВЕ) ---
        'btn_open_app': "🚀 Open DelivePro",
        'btn_dashboard': "📊 Dashboard",
        'btn_map': "🗺 Orders Map",
        'btn_report': "📊 Make Report",
        'btn_settings': "⚙️ Business Settings",
        'btn_staff': "👥 Staff",
        'btn_new_order': "📝 New Order",
        'btn_active_orders': "📂 Active Orders",
        'btn_my_deliveries': "📦 My Deliveries",
        'btn_boss_panel': "👑 Boss Panel"
    }
}

def get_text(lang_code: str, key: str, **kwargs) -> str:
    """Отримує переклад з TEXTS. Якщо мови нема - бере англійську. Дозволяє форматування."""
    lang = lang_code if lang_code in TEXTS else 'en'
    text = TEXTS[lang].get(key, TEXTS['en'].get(key, key))
    if kwargs:
        return text.format(**kwargs)
    return text
